Repository Team-HoiVin/toit, pull requests merged in 2024-12, with the labels that each got.

#8 fix: commit body case 추가
  commitlint.config.js
Labels: 이슈

#9 feat: input 공통 컴포넌트 구현
  public/icons/visibility_off.svg
  public/icons/visibility_on.svg
  src/components/button/PasswordButton.tsx
  src/components/input/Input.tsx
  tailwind.config.ts
Labels: 개발

#18 feat: middleware 수정
  next.config.mjs
  src/app/(auth)/login/_utils/mutation.ts
  src/app/(auth)/signup/_utils/mutation.ts
  src/app/not-found.tsx
  src/middleware.ts
Labels: 도움필요
